export { Download } from './ui/Download/Download'
export { Learn } from './ui/Learn/Learn'
export { Main } from './ui/Main/Main'
export { Steps } from './ui/Steps/Steps'
export { Trend } from './ui/Trend/Trend'
export { News } from './ui/News/News'
